from __future__ import annotations

AI_TITLES = {
    "ai engineer",
    "senior ai engineer",
    "lead ai engineer",
    "ml engineer",
    "machine learning engineer",
    "senior machine learning engineer",
    "applied ml engineer",
    "recommendation systems engineer",
    "search engineer",
    "nlp engineer",
    "senior nlp engineer",
    "senior software engineer (ml)",
    "data scientist",
    "senior data scientist",
}

ADJACENT_TITLES = {
    "backend engineer",
    "data engineer",
    "senior data engineer",
    "analytics engineer",
    "software engineer",
    "senior software engineer",
    "full stack developer",
    "cloud engineer",
    "devops engineer",
    "python developer",
    "java developer",
}

NON_TECH_TITLES = {
    "hr manager",
    "marketing manager",
    "sales executive",
    "accountant",
    "operations manager",
    "customer support",
    "graphic designer",
    "content writer",
    "civil engineer",
    "mechanical engineer",
    "project manager",
    "business analyst",
}

SERVICE_COMPANIES = {
    "tcs",
    "infosys",
    "wipro",
    "accenture",
    "cognizant",
    "capgemini",
    "mindtree",
    "hcl",
    "tech mahindra",
    "mphasis",
}

PRODUCT_COMPANIES = {
    "swiggy",
    "zomato",
    "razorpay",
    "cred",
    "flipkart",
    "meesho",
    "nykaa",
    "inmobi",
    "ola",
    "zoho",
    "freshworks",
    "policybazaar",
}

RETRIEVAL_TERMS = {
    "retrieval",
    "ranking",
    "ranker",
    "search",
    "recommendation",
    "recommender",
    "recommendations",
    "personalization",
    "personalisation",
    "matching",
    "bm25",
    "hybrid search",
    "semantic search",
    "candidate matching",
    "talent matching",
}

VECTOR_TERMS = {
    "embedding",
    "embeddings",
    "vector",
    "faiss",
    "pinecone",
    "weaviate",
    "qdrant",
    "milvus",
    "opensearch",
    "elasticsearch",
    "ann",
    "nearest neighbor",
    "nearest neighbour",
    "sentence-transformers",
    "bge",
    "e5",
}

ML_TERMS = {
    "machine learning",
    "ml",
    "ai",
    "llm",
    "rag",
    "nlp",
    "fine-tuning",
    "fine tuning",
    "lora",
    "qlora",
    "peft",
    "python",
    "pytorch",
    "tensorflow",
    "scikit",
    "xgboost",
    "lightgbm",
    "feature engineering",
    "model serving",
}

EVAL_TERMS = {
    "ndcg",
    "mrr",
    "map",
    "a/b",
    "ab test",
    "a/b test",
    "offline evaluation",
    "online evaluation",
    "evaluation framework",
    "offline metric",
    "online metric",
    "offline-to-online",
    "relevance",
    "precision",
    "recall",
}

PRODUCTION_TERMS = {
    "production",
    "deployed",
    "shipped",
    "real users",
    "scale",
    "latency",
    "index refresh",
    "regression",
    "user-facing",
    "real-time",
    "monitoring",
    "drift",
    "refresh",
    "pipeline",
    "served",
    "launched",
    "owned",
}

SHALLOW_AI_TERMS = {
    "curious about ai",
    "chatgpt",
    "ai tools",
    "productivity",
    "content creation",
    "experimented with",
}
